---
- name: Setting up server
  hosts: venus
  become: no

  pre_tasks:
    - name: Update and upgrade repositories.
      apt:
        update_cache=yes
        upgrade=yes
      become: yes

  roles:
#    - vim
#    - geerlingguy.docker
#    - docker-compose
#    - samba
    - duplicati
#    - haste-client
    - gitea
#    - qbittorrent
    - calibre-web
#    - haste-server
#    - jellyfin
