---
- name: Setting up server
  hosts: all
  become: true

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Update and upgrade repositories.
      apt:
        update_cache=yes
        upgrade=yes
    - name: Install vim
      apt:
        name: vim
        state: present
    - name: Configure vim
      get_url:
        url: "https://raw.githubusercontent.com/CalvoUTN/infra/master/vim/.vimrc"
        dest: "/home/venus/.vimrc"

  tasks:
    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Install docker-compose
      include: subtasks/docker-compose.yml
