---
- name: Setting up server
  hosts: venus
  become: true

  pre_tasks:
    - name: Update and upgrade repositories.
      apt:
        update_cache=yes
        upgrade=yes

  roles:
    - vim
    - docker
