---
# tasks file for samba
- name: Ensure samba client is installed.
  package:
    name: smbclient
    state: present

- name: Ensure samba mountpoint exists.
  file:
    path: /mnt/olimpo
    state: directory

- name: Mount samba share as Olimpo
  mount:
    src: //192.168.0.182/storage
    path: /mnt/olimpo
    fstype: cifs
    opts: "_netdev,username={{ smb_user }},password={{ smb_pass  }}"
    state: mounted
    
#- name: Mount smb share as olimpo
#  lineinfile:
#    path: /etc/fstab
#    state: present
#    insertafter: EOF
#    line: "//192.168.0.182/storage /mnt/olimpo cifs _netdev,username=zeus,password=calvo123 0 0"
#  notify: remounting fstab


    
