---
version: "2.1"
services:
  calibre-web:
    image: linuxserver/calibre-web:amd64-latest
    container_name: calibre-web
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Argentina/Cordoba
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - /home/dionisio/services/config/calibre-web:/config
      - /mnt/olimpo/Books/BibliotecaEPL:/books
    ports:
      - 8083:8083
    restart: unless-stopped
