version: '2'
services:
  web:
    image: gitea/gitea:latest
    volumes:
      - /home/vulcan/gitea/data:/data
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db
    restart: always
  db:
    image: linuxserver/mariadb:amd64-latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=prueba
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=prueba
    volumes:
      - /home/vulcan/gitea:/var/lib/mysql

# Added KaTeX support adding this: https://github.com/go-gitea/gitea/issues/3445#issuecomment-629644399
