---
# tasks file for media-containers
- name: Create needed directory.
  file:
    path: "{{ ansible_env.HOME }}/services"
    state: directory
    
- name: Copy docker-compose files.
  unarchive:
    src: ../files/docker-compose-files.tar.gz
    dest: "{{ ansible_env.HOME }}/services/"

- name: Configure qbittorrent
  lineinfile:
    path: "{{ ansible_env.HOME }}/services/config/qbittorrent/docker-compose.yml"
    regexp: 'config$'
    line: "     - {{ ansible_env.HOME }}/services/config/qbittorrent:/config"
  

- name: Configure Jellyfin
  import_tasks: jellyfin.yml
