---
# tasks file for gitea

- name: Make sure services/config/qbittorrent exists
  file:
    path: "{{ ansible_env.HOME  }}/services/config/qbittorrent"
    state: directory
  become: yes

- name: Make sure docker-compose.yml is in place.
  copy:
    src: ../files/docker-compose.yml
    dest: "{{ ansible_env.HOME  }}/services/config/qbittorrent"
    force: no
  become: yes

- name: Configure config directory.
  lineinfile:
    path: "{{ ansible_env.HOME  }}/services/config/qbittorrent/docker-compose.yml"
    regexp: '/config$'
    line: "      - {{ ansible_env.HOME }}/services/config/qbittorrent:/config"
  become: yes

- name: Start docker container.
  community.docker.docker_compose:
    project_src: "{{ ansible_env.HOME  }}/services/config/qbittorrent/"
  become: yes
