---
# tasks file for duplicati

- name: Make sure services/config/duplicati exists.
  file:
    path: "{{ ansible_env.HOME  }}/services/config/duplicati"
    state: directory
  become: yes

- name: Make sure docker-compose.yml is in place.
  copy:
    src: ../files/docker-compose.yml
    dest: "{{ ansible_env.HOME  }}/services/config/duplicati"
    force: no
  become: yes

- name: Configure config directory (1/3).
  lineinfile:
    path: "{{ ansible_env.HOME  }}/services/config/duplicati/docker-compose.yml"
    regexp: 'configfiles$'
    line: "      - {{ ansible_env.HOME }}/services/config/duplicati:/config #configfiles"
  become: yes

- name: Configure config directory (2/3).
  lineinfile:
    path: "{{ ansible_env.HOME  }}/services/config/duplicati/docker-compose.yml"
    regexp: 'backupstorage$'
    line: "      - {{ local_backup_dir }}:/ServicesBackedup #backupstorage"
  become: yes

- name: Configure config directory (3/3).
  lineinfile:
    path: "{{ ansible_env.HOME  }}/services/config/duplicati/docker-compose.yml"
    regexp: 'backupedfolder$'
    line: "      - {{ remote_backup_dir }}:/BackupStorage #backupedfolder"
  become: yes

- name: Copy remote-backup configuration
  copy:
    src: "../files/backup-local-config.json"
    dest: "{{ ansible_env.HOME  }}/services/config/duplicati"
  become: yes

- name: Copy remote-backup configuration.
  copy:
    src: "../files/backup-remote-config.json"
    dest: "{{ ansible_env.HOME  }}/services/config/duplicati"
    force: no
  become: yes

- name: Paste password to remote-backup configuration.
  lineinfile:
    path: "{{ ansible_env.HOME  }}/services/config/duplicati/backup-remote-config.json"
    regexp: 'placeholder'
    line: '       "Value": "{{ remote_password  }}",'
  become: yes

- name: Start docker container.
  community.docker.docker_compose:
    project_src: "{{ ansible_env.HOME  }}/services/config/duplicati/"
  become: yes
