---

version: "2.1"
services:
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Argentina/Cordoba
    volumes:
      - /home/venus/services/config/duplicati:/config  # configfiles
      - /mnt/olimpo/Backups/venus:/BackupStorage  # backupstorage
      - /home/venus/services:/ServicesBackedup  # backupedfolder
    ports:
      - 8200:8200
    restart: unless-stopped

