---
# tasks file for vim
- name: Ensure vim is installed.
  package:
    name: vim
    state: present
  become: yes

- name: Ensure latest dotfiles are deployed.
  get_url:
    url: "https://raw.githubusercontent.com/CalvoUTN/infra/master/roles/vim/files/.vimrc"
    dest: "~/.vimrc"
  become: no
    
