---
# tasks file for vim
- name: Ensure vim is installed.
  package:
    name: vim
    state: present
  become: yes

- name: Ensure latest dotfiles are deployed.
  copy:
    src: "../files/.vimrc"
    dest: "~/.vimrc"
  become: no

- name: Ensure .vim/autoload exists.
  file:
    path: "~/.vim/autoload"
    state: directory
  become: no
    
- name: Ensure vim-plug is installed.
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "~/.vim/autoload/plug.vim"
  become: no
